# Generated by Django 2.2 on 2019-10-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0003_auto_20191013_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='image',
        ),
    ]
