# Generated by Django 2.2 on 2019-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0004_auto_20191013_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
