# Generated by Django 2.2 on 2019-10-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0005_auto_20191013_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
