# Generated by Django 2.2 on 2019-10-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0006_auto_20191013_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_photo',
        ),
    ]
