# Generated by Django 2.2 on 2019-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0013_auto_20191013_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
