# Generated by Django 2.2 on 2019-10-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0020_auto_20191014_1026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='pics_post',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='pics_profile',
        ),
    ]
