# Generated by Django 2.2 on 2019-10-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0021_auto_20191014_1220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
