# Generated by Django 2.2 on 2019-10-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0023_auto_20191014_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
    ]
