# Generated by Django 2.2 on 2019-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pics', '0024_auto_20191014_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
