# Generated by Django 2.2 on 2019-10-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('Pics', '0029_auto_20191016_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
